# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: vokrut <vokrut@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/06/21 12:01:22 by vokrut            #+#    #+#              #
#    Updated: 2019/06/27 09:51:40 by vokrut           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM alpine

MAINTAINER vokrut "vokrut@student.42.us.org"

RUN apk update && apk upgrade && apk add vim

CMD ["vim"]