# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: vokrut <vokrut@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/06/26 21:39:11 by vokrut            #+#    #+#              #
#    Updated: 2019/06/27 14:16:29 by vokrut           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM debian:latest

MAINTAINER vokrut "vokrut@student.42.us.org"

RUN apt-get update && apt-get upgrade -y && apt-get install -y python vim git